name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g http-server
        
    - name: Validate HTML
      run: |
        echo "Validating HTML structure..."
        if [ ! -f "index.html" ]; then
          echo "index.html not found!"
          exit 1
        fi
        echo "HTML validation passed"
        
    - name: Test Firebase Config
      run: |
        echo "Testing Firebase configuration..."
        if [ ! -f "src/js/config.js" ]; then
          echo "Firebase config not found!"
          exit 1
        fi
        echo "Firebase config found"
        
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4
      if: github.ref == 'refs/heads/main'
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/main'
      with:
        path: .
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main'